import Synthesis.Domains.Electronics
import Synthesis.Domains.Electronics.Analytic
import Synthesis.Domains.Thermal
import Synthesis.Domains.Mechanics
import Synthesis.Domains.Photonics
import Synthesis.Domains.Chemistry
import Synthesis.Domains.Quantum
import Synthesis.Domains.Components
import Synthesis.Domains.RealElectronics
